//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLU.Datos.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class modelEntities : DbContext
    {
        public modelEntities()
            : base("name=modelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Domicilio> Domicilio { get; set; }
        public virtual DbSet<MedioDeVidaLicito> MedioDeVidaLicito { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<SolicitudLegitimoUsuario> SolicitudLegitimoUsuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
