//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLU.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicilio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Domicilio()
        {
            this.SolicitudLegitimoUsuario = new HashSet<SolicitudLegitimoUsuario>();
            this.SolicitudLegitimoUsuario1 = new HashSet<SolicitudLegitimoUsuario>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int IDDomicilio { get; set; }
        public string Calle { get; set; }
        public int NumeroCalle { get; set; }
        public Nullable<int> Piso { get; set; }
        public string Departamento { get; set; }
        public string Provincia { get; set; }
        public string Localidad { get; set; }
        public int CodigoPostal { get; set; }
        public string DatosAdicionales { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudLegitimoUsuario> SolicitudLegitimoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudLegitimoUsuario> SolicitudLegitimoUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
