//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLU.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.SolicitudLegitimoUsuario = new HashSet<SolicitudLegitimoUsuario>();
        }
    
        public int IDUsuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int CUIL { get; set; }
        public int Telefono { get; set; }
        public string Mail { get; set; }
        public int DomicilioEspecial { get; set; }
        public string ApellidoMaterno { get; set; }
        public int MedioDeVidaLicito { get; set; }
        public string Fuerza { get; set; }
        public string Nacionalidad { get; set; }
        public Nullable<bool> IdoneidadTiro { get; set; }
        public Nullable<bool> AptoFisico { get; set; }
        public Nullable<bool> AptoPsico { get; set; }
    
        public virtual Domicilio Domicilio { get; set; }
        public virtual MedioDeVidaLicito MedioDeVidaLicito1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudLegitimoUsuario> SolicitudLegitimoUsuario { get; set; }
    }
}
